// index.js — SuperApp Backend (Full Tencent Payment Flow)
require("dotenv").config();
const express = require("express");
const crypto  = require("crypto");
const https   = require("https");
const http    = require("http");
const { v4: uuidv4 } = require("uuid");

const { captureMiddleware } = require("./logger");
const dashboard             = require("./dashboard");
const serverDashboard       = require("./serverDashboard");

const app = express();
app.use((req, res, next) => { res.setHeader("ngrok-skip-browser-warning", "true"); next(); });
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use(captureMiddleware);
app.use(dashboard);
app.use("/serverDashboard", serverDashboard);
app.use((req, res, next) => {
  if (req.path === "/dashboard" || req.path.startsWith("/logs")) return next();
  console.log(`\n[SUPERAPP] ${new Date().toISOString()} ${req.method} ${req.path}`);
  console.log("  Body:", JSON.stringify(req.body, null, 2));
  next();
});

// ── ENV ──────────────────────────────────────────────────────
const SECRET_KEY         = process.env.APP_ENCRYPT_KEY    || "0123456789abcdef0123456789abcdef";
const NOTIFY_SECRET      = process.env.NOTIFY_SECRET      || "superapp_miniapp_shared_secret_2026";
const MINIAPP_BACKEND_URL= process.env.MINIAPP_BACKEND_URL|| "https://tencentminiapptesting.xyz/miniapp";
const COFFEE_BACKEND_URL = process.env.COFFEE_BACKEND_URL || "https://tencentminiapptesting.xyz/coffee";
const TCSAS_OPENSERVER   = process.env.TCSAS_OPENSERVER   || "https://openapi-sg.tcmpp.com/openserver";

// ── Payment credentials (UOB as payment processor) ──────────
// These are generated by UOB and stored server-side only
// Load private key from file (more reliable than .env for multiline)
const fs = require('fs');
const MERCHANT_PRIVATE_KEY = (() => {
  const keyFile = process.env.MERCHANT_PRIVATE_KEY_FILE || '/root/merchant_private_key.pem';
  try { return fs.readFileSync(keyFile, 'utf8'); }
  catch { return process.env.MERCHANT_PRIVATE_KEY || ''; }
})();
const MERCHANT_CERT_SERIAL = process.env.MERCHANT_CERT_SERIAL || "65032F5287CAC43DA2D9273A14D15E4C97B43DAB";
const MERCHANT_ID          = process.env.MERCHANT_ID          || "MERCHANT_STARBUCKS_001";
const APIV3_KEY            = process.env.APIV3_KEY            || "UOBTmrwCoffeePayKey2026SGD12345";

// ── Mini app routing ─────────────────────────────────────────
const MINIAPP_BACKEND_MAP = {
  "mpvc3tdaldpq7zpu": MINIAPP_BACKEND_URL,
  "mpapkxdfqzgbvj67": COFFEE_BACKEND_URL,
};
function getMiniAppBackendUrl(appid) {
  if (!appid) return MINIAPP_BACKEND_URL;
  return MINIAPP_BACKEND_MAP[appid] || MINIAPP_BACKEND_URL;
}

// ── Helpers ──────────────────────────────────────────────────
function verifyTCSignature(tcTimestamp, tcSignature) {
  try {
    const key     = Buffer.from(SECRET_KEY.substring(0, 32).padEnd(32, "0"), "utf8");
    const ts      = Buffer.from(tcTimestamp, "utf8");
    const padding = 16 - (ts.length % 16);
    const padded  = Buffer.concat([ts, Buffer.alloc(padding, padding)]);
    const cipher  = crypto.createCipheriv("aes-256-ecb", key, null);
    cipher.setAutoPadding(false);
    return Buffer.concat([cipher.update(padded), cipher.final()]).toString("hex") === tcSignature;
  } catch { return false; }
}

function httpPost(url, body, headers = {}) {
  return new Promise((resolve, reject) => {
    const payload = JSON.stringify(body);
    const urlObj  = new URL(url);
    const options = {
      hostname: urlObj.hostname,
      port: urlObj.port || (url.startsWith("https") ? 443 : 80),
      path: urlObj.pathname + urlObj.search,
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Content-Length": Buffer.byteLength(payload),
        ...headers
      }
    };
    const client = url.startsWith("https") ? https : http;
    const req = client.request(options, (res) => {
      let data = "";
      res.on("data", (c) => (data += c));
      res.on("end", () => { try { resolve(JSON.parse(data)); } catch { resolve({ raw: data }); } });
    });
    req.on("error", reject);
    req.write(payload);
    req.end();
  });
}

// ── paySign generation (for wx.requestPayment) ────────────────
function generatePaySign(appid, timestamp, nonceStr, prepayId) {
  const message = `${appid}\n${timestamp}\n${nonceStr}\n${prepayId}\n`;
  const sign = crypto.createSign("RSA-SHA256");
  sign.update(message);
  const signed = sign.sign(MERCHANT_PRIVATE_KEY, "base64");
  return Buffer.from(signed, "base64").toString("base64");
}

// ── AES-256-GCM decrypt (for SAS payment callback) ────────────
function decryptAESGCM(ciphertext, nonce, associatedData) {
  const key        = Buffer.from(APIV3_KEY, "utf8");
  const cipherBuf  = Buffer.from(ciphertext, "base64");
  const authTag    = cipherBuf.slice(cipherBuf.length - 16);
  const encrypted  = cipherBuf.slice(0, cipherBuf.length - 16);
  const decipher   = crypto.createDecipheriv("aes-256-gcm", key, Buffer.from(nonce, "utf8"));
  decipher.setAuthTag(authTag);
  decipher.setAAD(Buffer.from(associatedData || "", "utf8"));
  return Buffer.concat([decipher.update(encrypted), decipher.final()]).toString("utf8");
}

// ── ok / fail helpers ─────────────────────────────────────────
const ok   = (data, res) => res.json({ code: 200, ...data, requestId: uuidv4() });
const fail = (code, msg, res) => res.json({ returnCode: code, returnMessage: msg, requestId: uuidv4() });

// ═══════════════════════════════════════════════════════════════
// STAGE 1: Pre-order — Superapp backend implements
// POST /v3/pay/transactions/jsapi
// SAS receives from MP backend, forwards here, we return prepay_id
// ═══════════════════════════════════════════════════════════════
app.post("/v3/pay/transactions/jsapi", async (req, res) => {
  // mchid comes from Authorization header (not body per Tencent spec)
  const authHeader = req.headers["authorization"] || "";
  const mchidMatch = authHeader.match(/mchid="([^"]+)"/);
  const mchid = mchidMatch ? mchidMatch[1] : (req.body.mchid || MERCHANT_ID);
  const { appid, description, out_trade_no, notify_url, amount, payer, detail } = req.body;
  console.log(`  [/v3/pay/transactions/jsapi] order from SAS — appid=${appid} mchid=${mchid} out_trade_no=${out_trade_no}`);

  if (!appid || !mchid || !out_trade_no || !amount || !payer) {
    return res.status(400).json({ code: "PARAM_ERROR", message: "Missing required fields" });
  }

  // Generate prepay_id (UOB payment system)
  const prepay_id = `prepay_${Date.now()}_${crypto.randomBytes(8).toString("hex")}`;

  // Store order for later verification
  const orderStore = global.orderStore || (global.orderStore = {});
  orderStore[out_trade_no] = {
    prepay_id, appid, mchid, description, out_trade_no,
    notify_url, amount, payer, detail,
    status: "PENDING", created_at: Date.now()
  };

  console.log(`  [/v3/pay/transactions/jsapi] prepay_id=${prepay_id} ✅`);
  // SAS expects: returnCode, data.prepayId, requestId
  return res.json({
    returnCode:    "0",
    returnMessage: "success",
    data:          { prepayId: prepay_id },
    requestId:     uuidv4()
  });
});

// ═══════════════════════════════════════════════════════════════
// STAGE 2: Payment — validate able to pay
// POST /payment/validate
// Superapp client calls this after SDK forwards requestPayment
// ═══════════════════════════════════════════════════════════════
app.post("/payment/validate", async (req, res) => {
  const { prepay_id, appid, openid } = req.body;
  console.log(`  [/payment/validate] prepay_id=${prepay_id} appid=${appid}`);

  const orderStore = global.orderStore || {};
  const order = Object.values(orderStore).find(o => o.prepay_id === prepay_id);

  if (!order) {
    return res.json({ returnCode: "0", valid: false, message: "Order not found" });
  }

  // UOB banking validation — check user has sufficient balance
  // For POC: always valid
  console.log(`  [/payment/validate] order found — amount=${order.amount?.total} ${order.amount?.currency} ✅`);
  return res.json({
    returnCode: "0",
    valid: true,
    actualAmount: order.amount?.total || 0,
    currency: order.amount?.currency || "SGD",
    description: order.description,
    requestId: uuidv4()
  });
});

// ═══════════════════════════════════════════════════════════════
// STAGE 2: Payment — confirm payment
// POST /payment/confirm
// Called after user enters auth and confirms payment
// ═══════════════════════════════════════════════════════════════
app.post("/payment/confirm", async (req, res) => {
  const { prepay_id, appid, openid } = req.body;
  console.log(`  [/payment/confirm] prepay_id=${prepay_id} appid=${appid}`);

  const orderStore = global.orderStore || {};
  const order = Object.values(orderStore).find(o => o.prepay_id === prepay_id);

  if (!order) return res.json({ returnCode: "1001", returnMessage: "Order not found" });

  // Verify payment information (UOB banking side)
  // For POC: always success
  order.status      = "SUCCESS";
  order.paid_at     = Date.now();
  order.transaction_id = `txn_${Date.now()}_${crypto.randomBytes(4).toString("hex")}`;

  console.log(`  [/payment/confirm] payment verified ✅ transaction_id=${order.transaction_id}`);

  // ═══ STAGE 3 SHIPMENT: Superapp backend → SAS backend ═══════
  // After confirming payment, notify SAS so SAS can deliver to MP backend
  // SAS will then async retry notify MP backend /notify_payBack
  setImmediate(async () => {
    try {
      await notifySASPaymentResult(order);
    } catch (err) {
      console.error("  [/payment/confirm] SAS notification failed:", err.message);
    }
  });

  return res.json({
    returnCode: "0",
    returnMessage: "Payment confirmed",
    transaction_id: order.transaction_id,
    out_trade_no: order.out_trade_no,
    requestId: uuidv4()
  });
});

// ═══════════════════════════════════════════════════════════════
// STAGE 3: Shipment — Superapp backend → SAS backend
// This triggers SAS to async notify MP backend
// ═══════════════════════════════════════════════════════════════
async function notifySASPaymentResult(order) {
  const url  = `${TCSAS_OPENSERVER}/pay/paymentnotify`;
  const body = JSON.stringify({
    appid:          order.appid,
    mchid:          order.mchid,
    out_trade_no:   order.out_trade_no,
    transaction_id: order.transaction_id,
    trade_state:    "SUCCESS",
    amount:         order.amount,
    payer:          order.payer,
    notify_url:     order.notify_url,
  });

  const timestamp = Math.floor(Date.now() / 1000).toString();
  const nonce     = crypto.randomBytes(16).toString("hex").toUpperCase();
  const tcTimestamp = Date.now().toString();
  const tcSig = (() => {
    const key     = Buffer.from(SECRET_KEY.substring(0, 32).padEnd(32, "0"), "utf8");
    const ts      = Buffer.from(tcTimestamp, "utf8");
    const padding = 16 - (ts.length % 16);
    const padded  = Buffer.concat([ts, Buffer.alloc(padding, padding)]);
    const cipher  = crypto.createCipheriv("aes-256-ecb", key, null);
    cipher.setAutoPadding(false);
    return Buffer.concat([cipher.update(padded), cipher.final()]).toString("hex");
  })();

  console.log(`  [notifySASPaymentResult] POST ${url}`);
  try {
    const result = await httpPost(url, JSON.parse(body), {
      "x-tc-timestamp": tcTimestamp,
      "x-tc-signature": tcSig,
    });
    console.log(`  [notifySASPaymentResult] SAS response:`, JSON.stringify(result));

    // If SAS is unavailable or returns error, fall back to direct notify
    if (!result || result.returnCode !== "0") {
      console.log(`  [notifySASPaymentResult] SAS unavailable — fallback direct notify to MP backend`);
      await directNotifyMPBackend(order);
    }
  } catch (err) {
    console.error(`  [notifySASPaymentResult] SAS call failed: ${err.message} — fallback direct notify`);
    await directNotifyMPBackend(order);
  }
}

// Fallback: direct notify MP backend (if SAS unavailable)
async function directNotifyMPBackend(order) {
  const targetBackend = getMiniAppBackendUrl(order.appid);
  const event_type    = "TRANSACTION.SUCCESS";
  const payload       = `${order.out_trade_no}:${order.prepay_id}:${event_type}`;
  const signature     = crypto.createHmac("sha256", NOTIFY_SECRET).update(payload).digest("hex");
  try {
    await httpPost(`${targetBackend}/notify_payBack`, {
      event_type, out_trade_no: order.out_trade_no,
      prepay_id: order.prepay_id, appid: order.appid, signature,
    });
    console.log(`  [directNotifyMPBackend] MP backend notified ✅`);
  } catch (err) {
    console.error(`  [directNotifyMPBackend] failed:`, err.message);
  }
}

// ═══════════════════════════════════════════════════════════════
// STAGE 3: SAS → Superapp backend payment result notification
// SAS calls this after receiving our notification
// POST /payment/notify
// ═══════════════════════════════════════════════════════════════
app.post("/payment/notify", async (req, res) => {
  const tcTimestamp = req.headers["x-tc-timestamp"] || req.headers["tc-timestamp"] || "";
  const tcSignature = req.headers["x-tc-signature"] || req.headers["tc-signature"] || "";

  if (tcTimestamp && tcSignature) {
    if (!verifyTCSignature(tcTimestamp, tcSignature)) {
      console.error("  [/payment/notify] Invalid tc-signature — rejecting");
      return res.json({ returnCode: "1003", returnMessage: "Invalid signature", requestId: uuidv4() });
    }
    console.log("  [/payment/notify] tc-signature verified ✅ (SAS Passthrough call)");
  } else {
    console.log("  [/payment/notify] No tc-signature — direct Android call");
  }

  const { out_trade_no, prepay_id, openid, amount, status, appid } = req.body;
  if (!out_trade_no) return res.json({ returnCode: "1001", returnMessage: "Missing out_trade_no", requestId: uuidv4() });

  const event_type   = status === "FAILED" ? "TRANSACTION.FAIL" : "TRANSACTION.SUCCESS";
  const targetBackend = getMiniAppBackendUrl(appid);
  console.log(`  [/payment/notify] appid=${appid} routing to ${targetBackend}`);

  try {
    const payload   = `${out_trade_no}:${prepay_id}:${event_type}`;
    const signature = crypto.createHmac("sha256", NOTIFY_SECRET).update(payload).digest("hex");
    await httpPost(`${targetBackend}/notify_payBack`, {
      event_type, out_trade_no, prepay_id, appid, signature,
    });
    console.log(`  [/payment/notify] MP backend notified ✅`);
  } catch (err) {
    console.error("  [/payment/notify] MP backend notify failed:", err.message);
  }

  return res.json({ returnCode: "0", returnMessage: "ok", requestId: uuidv4() });
});

// ═══════════════════════════════════════════════════════════════
// STAGE 3: SAS → MP backend async retry (SAS calls notify_url directly)
// This is handled by coffee-miniapp-backend /notify_payBack
// Superapp backend receives the ACK confirmation from SAS
// POST /payment/notify/ack
// ═══════════════════════════════════════════════════════════════
app.post("/payment/notify/ack", async (req, res) => {
  console.log(`  [/payment/notify/ack] SAS ack received`);
  return res.json({ returnCode: "0", returnMessage: "ok", requestId: uuidv4() });
});

// ── Existing login endpoints ──────────────────────────────────
app.post("/user/checkUser", async (req, res) => {
  const tcTimestamp = req.headers["x-tc-timestamp"] || req.headers["tc-timestamp"] || "";
  const tcSignature = req.headers["x-tc-signature"] || req.headers["tc-signature"] || "";
  if (tcTimestamp && tcSignature && !verifyTCSignature(tcTimestamp, tcSignature)) {
    return res.json({ returnCode: "1003", returnMessage: "Invalid signature", requestId: uuidv4() });
  }
  const { accountid } = req.body;
  console.log(`  [checkUser] accountid=${accountid}`);
  return res.json({ returnCode: "0", data: true, requestId: uuidv4() });
});

app.post("/user/getUserInfoTemporaryCode", async (req, res) => {
  return res.json({ returnCode: "0", data: { temporaryCode: uuidv4() }, requestId: uuidv4() });
});
app.post("/user/getUserEmail", async (req, res) => {
  return res.json({ returnCode: "0", data: { encryptedEmail: "" }, requestId: uuidv4() });
});
app.post("/user/getUserPhoneNumber", async (req, res) => {
  return res.json({ returnCode: "0", data: { encryptedPhone: "" }, requestId: uuidv4() });
});
app.post("/user/getUserNick", async (req, res) => {
  return res.json({ returnCode: "0", data: { nick: "UOB User" }, requestId: uuidv4() });
});

app.get("/health", (req, res) => res.json({ status: "ok", service: "superapp-backend", version: "2.0.0-payment" }));

const PORT = process.env.SUPERAPP_PORT || 3001;
app.listen(PORT, () => console.log(`[SUPERAPP] listening on port ${PORT}`));
