// ============================================================
// miniapp-backend/index.js  — TCSAS Payment Integration
// Flow:  Mini Program → POST /payOrderV3 → SAS /v3/pay/transactions/jsapi
//        → generates real paySign → returns to mini program
//        SAS → POST /notify_payBack  (delivery notification + ACK)
//        Mini Program → POST /queryPayResult  (optional polling)
// ============================================================

require("dotenv").config();
const express = require("express");
const crypto = require("crypto");
const https = require("https");
const http = require("http");
const { v4: uuidv4 } = require("uuid");

const app = express();

app.use((req, res, next) => {
  res.setHeader("ngrok-skip-browser-warning", "true");
  next();
});

app.use(express.json());
app.use(express.urlencoded({ extended: true }));

// ── ENV config ────────────────────────────────────────────────
// Required in .env:
//   TCSAS_OPENSERVER=https://api-sg.tcmpp.com
//   APPSECRET=83cf804d539a0b954c2a8119ca17063b
//   JWT_SECRET=change_this_to_a_random_secret_string
//   APPID=mpvc3tdaldpq7zpu
//   MINIAPP_BACKEND_URL=https://tencentminiapptesting.xyz/miniapp
//   MERCHANT_PRIVATE_KEY=-----BEGIN PRIVATE KEY-----\n...\n-----END PRIVATE KEY-----
//   MINIAPP_PORT=3000
const TCSAS_OPENSERVER    = process.env.TCSAS_OPENSERVER    || "https://api-sg.tcmpp.com";
const APPSECRET           = process.env.APPSECRET           || "YOUR_APPSECRET_FROM_TCSAS_CONSOLE";
const JWT_SECRET          = process.env.JWT_SECRET          || "change_this_to_a_random_secret_string";
const APPID               = process.env.APPID               || "mpvc3tdaldpq7zpu";
const MINIAPP_BACKEND_URL = process.env.MINIAPP_BACKEND_URL || "https://tencentminiapptesting.xyz/miniapp";
// RSA private key generated by merchant during onboarding (Phase 2 in TCSAS docs)
// Used to sign the paySign string for wx.requestPayment()
const MERCHANT_PRIVATE_KEY = process.env.MERCHANT_PRIVATE_KEY || null;

// ── Logging ───────────────────────────────────────────────────
app.use((req, res, next) => {
  console.log(`\n[MINIAPP] ${new Date().toISOString()} ${req.method} ${req.path}`);
  console.log("  Body:", JSON.stringify(req.body, null, 2));
  next();
});

// ── In-memory users & orders ──────────────────────────────────
const users  = {};  // keyed by openid
const orders = {};  // keyed by out_trade_no

// ── Simple JWT ────────────────────────────────────────────────
function createToken(payload) {
  const header = Buffer.from(JSON.stringify({ alg: "HS256", typ: "JWT" })).toString("base64url");
  const body   = Buffer.from(
    JSON.stringify({ ...payload, iat: Date.now(), exp: Date.now() + 7 * 24 * 60 * 60 * 1000 })
  ).toString("base64url");
  const sig = crypto.createHmac("sha256", JWT_SECRET).update(`${header}.${body}`).digest("base64url");
  return `${header}.${body}.${sig}`;
}

function verifyToken(token) {
  try {
    const [header, body, sig] = token.split(".");
    const expectedSig = crypto
      .createHmac("sha256", JWT_SECRET)
      .update(`${header}.${body}`)
      .digest("base64url");
    if (sig !== expectedSig) throw new Error("Invalid signature");
    const payload = JSON.parse(Buffer.from(body, "base64url").toString());
    if (payload.exp < Date.now()) throw new Error("Token expired");
    return payload;
  } catch (e) {
    return null;
  }
}

// ── HTTP helpers ──────────────────────────────────────────────
function httpGet(url) {
  return new Promise((resolve, reject) => {
    const client = url.startsWith("https") ? https : http;
    client.get(url, (res) => {
      let data = "";
      res.on("data", (c) => (data += c));
      res.on("end", () => {
        try { resolve(JSON.parse(data)); }
        catch (e) { resolve({ raw: data }); }
      });
    }).on("error", reject);
  });
}

function httpPost(url, body) {
  return new Promise((resolve, reject) => {
    const payload   = JSON.stringify(body);
    const urlObj    = new URL(url);
    const options   = {
      hostname: urlObj.hostname,
      port:     urlObj.port || (url.startsWith("https") ? 443 : 80),
      path:     urlObj.pathname + urlObj.search,
      method:   "POST",
      headers:  {
        "Content-Type":   "application/json",
        "Content-Length": Buffer.byteLength(payload),
      },
    };
    const client  = url.startsWith("https") ? https : http;
    const req     = client.request(options, (res) => {
      let data = "";
      res.on("data", (c) => (data += c));
      res.on("end", () => {
        try { resolve(JSON.parse(data)); }
        catch (e) { resolve({ raw: data }); }
      });
    });
    req.on("error", reject);
    req.write(payload);
    req.end();
  });
}

// ── paySign generation (TCSAS spec, RSA-SHA256) ───────────────
// string2sign = {appId}\n{timeStamp}\n{nonceStr}\n{prepayId}\n
// signed with merchant RSA private key → base64
function generatePaySign(appId, timeStamp, nonceStr, prepayId) {
  if (!MERCHANT_PRIVATE_KEY) {
    // Development fallback — NOT for production
    console.warn(
      "  [paySign] ⚠️  MERCHANT_PRIVATE_KEY not set. Using MOCK paySign. " +
      "Set MERCHANT_PRIVATE_KEY in .env for production."
    );
    return `MOCK_PAY_SIGN_${crypto.randomBytes(8).toString("hex")}`;
  }
  const string2sign = `${appId}\n${timeStamp}\n${nonceStr}\n${prepayId}\n`;
  const sign = crypto.createSign("RSA-SHA256");
  sign.update(string2sign);
  return sign.sign(MERCHANT_PRIVATE_KEY, "base64");
}

// ──────────────────────────────────────────────────────────────
// POST /getUserInfo  (login — unchanged from original)
// ──────────────────────────────────────────────────────────────
app.post("/getUserInfo", async (req, res) => {
  const { appid, code } = req.body;
  if (!appid) return res.json({ code: 400, data: { msg: "Missing appid" } });
  if (!code)  return res.json({ code: 400, data: { msg: "Missing code" } });

  const url =
    `${TCSAS_OPENSERVER}/sns/jscode2session` +
    `?appid=${appid}&secret=${APPSECRET}&js_code=${code}&grant_type=authorization_code`;

  console.log("  Calling jscode2session:", url);

  let sessionData;
  try {
    sessionData = await httpGet(url);
    console.log("  jscode2session response:", JSON.stringify(sessionData));
  } catch (err) {
    return res.json({ code: 500, data: { msg: "Failed to contact TCSAS: " + err.message } });
  }

  if (sessionData.errcode && sessionData.errcode !== 0) {
    return res.json({ code: 401, data: { msg: `TCSAS error ${sessionData.errcode}: ${sessionData.errmsg}` } });
  }

  const { openid } = sessionData;
  if (!openid) return res.json({ code: 401, data: { msg: "No openid returned" } });

  let user = users[openid];
  if (!user) {
    user = {
      openid,
      id:        uuidv4(),
      userName:  `User_${openid.substring(0, 8)}`,
      avatarUrl: "https://picsum.photos/100",
      phone:     "",
      email:     "",
      createdAt: Date.now(),
    };
    users[openid] = user;
    console.log(`  New user created: openid=${openid}`);
  }

  const token = createToken({ openid, userId: user.id });

  return res.json({
    code: 200,
    data: {
      userName:  user.userName,
      token,
      id:        user.id,
      avatarUrl: user.avatarUrl,
      phone:     user.phone,
      email:     user.email,
      account:   openid,
    },
  });
});

// ──────────────────────────────────────────────────────────────
// POST /payOrderV3  — Stage 1: Pre-order generation
//
// Called by: Mini program frontend (via utils/fetch.js commonPay)
// This endpoint:
//   1. Validates JWT token
//   2. Calls SAS /v3/pay/transactions/jsapi to get prepayId
//   3. Generates paySign using merchant RSA private key
//   4. Returns payment params to mini program for wx.requestPayment()
// ──────────────────────────────────────────────────────────────
app.post("/payOrderV3", async (req, res) => {
  const { goods_detail, discount = 0, token, appid } = req.body;

  // ── 1. Auth ────────────────────────────────────────────────
  if (!token) return res.json({ code: 401, data: { msg: "Missing token — please login first" } });
  const payload = verifyToken(token);
  if (!payload) return res.json({ code: 401, data: { msg: "Invalid or expired token" } });
  const user = users[payload.openid];
  if (!user) return res.json({ code: 401, data: { msg: "User not found" } });

  if (!goods_detail || goods_detail.length === 0) {
    return res.json({ code: 400, data: { msg: "No goods in order" } });
  }

  // ── 2. Build order ─────────────────────────────────────────
  const out_trade_no = `order_${Date.now()}_${crypto.randomBytes(4).toString("hex")}`;
  const timeStamp    = Math.floor(Date.now() / 1000).toString();
  const nonceStr     = crypto.randomBytes(10).toString("hex");

  // Calculate total amount in cents (unit_price is in dollars, ×100 for cents)
  const totalCents = goods_detail.reduce(
    (sum, item) => sum + Math.round((item.unit_price || 0) * 100) * (item.quantity || 1),
    0
  );
  const discountCents = Math.round(discount * 100);
  const finalAmount   = Math.max(totalCents - discountCents, 1); // minimum 1 cent

  console.log(`  [payOrderV3] out_trade_no=${out_trade_no} amount=${finalAmount} openid=${payload.openid}`);

  // ── 3. Call SAS to get prepayId ────────────────────────────
  // SAS endpoint: POST /v3/pay/transactions/jsapi
  // SAS will forward to superapp-backend /v3/pay/transactions/jsapi
  const sasPayload = {
    appid:         APPID,
    description:   goods_detail.map((g) => g.goods_name).join(", ").substring(0, 100),
    out_trade_no,
    notify_url:    `${MINIAPP_BACKEND_URL}/notify_payBack`,
    amount: {
      total:    finalAmount,
      currency: "SGD",        // adjust currency for your region
    },
    payer: {
      openid: payload.openid,
    },
    goods_detail,
  };

  let prepayId;
  try {
    console.log(`  [payOrderV3] Calling SAS /v3/pay/transactions/jsapi ...`);
    const sasResp = await httpPost(
      `${TCSAS_OPENSERVER}/v3/pay/transactions/jsapi`,
      sasPayload
    );
    console.log(`  [payOrderV3] SAS response:`, JSON.stringify(sasResp));

    // SAS returns { returnCode: "0", data: { prepayId: "..." } }
    if (sasResp.returnCode !== "0" && sasResp.code !== 200) {
      console.error("  [payOrderV3] SAS returned error:", JSON.stringify(sasResp));
      // ── Development fallback: if SAS not reachable, use mock prepayId ──
      prepayId = `prepay_mock_${Date.now()}_${crypto.randomBytes(8).toString("hex")}`;
      console.warn("  [payOrderV3] Using MOCK prepayId (SAS not reachable in dev)");
    } else {
      prepayId = sasResp.data?.prepayId || sasResp.prepayId;
      if (!prepayId) {
        console.error("  [payOrderV3] No prepayId in SAS response. Using mock.");
        prepayId = `prepay_mock_${Date.now()}_${crypto.randomBytes(8).toString("hex")}`;
      }
    }
  } catch (err) {
    console.error("  [payOrderV3] SAS call failed:", err.message);
    // Development fallback
    prepayId = `prepay_mock_${Date.now()}_${crypto.randomBytes(8).toString("hex")}`;
    console.warn("  [payOrderV3] Using MOCK prepayId (SAS unreachable)");
  }

  // ── 4. Generate paySign with merchant RSA private key ──────
  // Per TCSAS docs: string2sign = appId\ntimeStamp\nnonceStr\nprepayId\n
  const paySign = generatePaySign(APPID, timeStamp, nonceStr, prepayId);

  // ── 5. Save order state for later notification/polling ─────
  orders[out_trade_no] = {
    out_trade_no,
    openid:     payload.openid,
    prepayId,
    status:     "PENDING",   // PENDING | SUCCESS | FAILED
    amount:     finalAmount,
    goods:      goods_detail,
    createdAt:  Date.now(),
  };

  console.log(`  [payOrderV3] SUCCESS prepayId=${prepayId}`);

  // ── 6. Return to mini program ──────────────────────────────
  // Mini program passes these directly to wx.requestPayment()
  return res.json({
    code:      200,
    timeStamp,
    nonceStr,
    package:   `prepay_id=${prepayId}`,
    signType:  "RSA",
    paySign,
    // Extra: pass out_trade_no so frontend can poll later
    out_trade_no,
  });
});

// ──────────────────────────────────────────────────────────────
// POST /notify_payBack  — Stage 3: Delivery notification
//
// Called by: SAS backend (asynchronous, retries for 24h)
// SAS sends payment result here after user completes payment.
// We MUST return { code: 200 } (ACK) to stop retries.
// ──────────────────────────────────────────────────────────────
app.post("/notify_payBack", (req, res) => {
  console.log("  [notify_payBack] Received payment notification");
  console.log("  [notify_payBack] Headers:", JSON.stringify(req.headers, null, 2));
  console.log("  [notify_payBack] Body:", JSON.stringify(req.body, null, 2));

  // SAS notification body contains:
  // {
  //   event_type: "TRANSACTION.SUCCESS" | "TRANSACTION.FAIL",
  //   resource: {
  //     algorithm: "AEAD_AES_256_GCM",
  //     ciphertext: "<AES encrypted payment result>",   // decrypt with AES key from TCSAS console
  //     nonce: "...",
  //     associated_data: "..."
  //   },
  //   create_time: "...",
  //   id: "<notification ID>"
  // }

  const { event_type, resource, out_trade_no } = req.body;

  // ── Option A: Plaintext out_trade_no (for dev/testing) ─────
  if (out_trade_no) {
    const order = orders[out_trade_no];
    if (order) {
      order.status = event_type === "TRANSACTION.SUCCESS" ? "SUCCESS" : "FAILED";
      order.notifiedAt = Date.now();
      console.log(`  [notify_payBack] Updated order ${out_trade_no} → ${order.status}`);
    }
  }

  // ── Option B: Encrypted resource (production) ──────────────
  // In production, SAS encrypts the payment result with your AES key.
  // You would decrypt it like this:
  //
  // const AES_KEY = process.env.MERCHANT_AES_KEY; // from TCSAS console
  // const { ciphertext, nonce, associated_data } = resource;
  // const decipher = crypto.createDecipheriv(
  //   "aes-256-gcm",
  //   Buffer.from(AES_KEY, "base64"),
  //   Buffer.from(nonce, "base64")
  // );
  // decipher.setAAD(Buffer.from(associated_data || "", "utf8"));
  // decipher.setAuthTag(Buffer.from(ciphertext.slice(-32), "base64"));  // last 16 bytes
  // const decrypted = Buffer.concat([
  //   decipher.update(Buffer.from(ciphertext.slice(0, -32), "base64")),
  //   decipher.final()
  // ]).toString("utf8");
  // const paymentResult = JSON.parse(decrypted);
  // Update order status based on paymentResult.trade_state

  // ── CRITICAL: Return ACK to stop SAS retries ───────────────
  // SAS retries delivery for 24h. Returning code:200 stops retries.
  return res.json({ code: 200, message: "OK" });
});

// ──────────────────────────────────────────────────────────────
// POST /queryPayResult  — Stage 4: Optional polling
//
// Called by: Mini program pay-result page (poll to confirm)
// Returns order status that mini program can show to user
// ──────────────────────────────────────────────────────────────
app.post("/queryPayResult", (req, res) => {
  const { out_trade_no, token } = req.body;

  if (!token) return res.json({ code: 401, data: { msg: "Missing token" } });
  const payload = verifyToken(token);
  if (!payload) return res.json({ code: 401, data: { msg: "Invalid token" } });

  if (!out_trade_no) return res.json({ code: 400, data: { msg: "Missing out_trade_no" } });

  const order = orders[out_trade_no];
  if (!order) return res.json({ code: 404, data: { msg: "Order not found" } });

  // Security: only the order owner can query
  if (order.openid !== payload.openid) {
    return res.json({ code: 403, data: { msg: "Unauthorized" } });
  }

  console.log(`  [queryPayResult] out_trade_no=${out_trade_no} status=${order.status}`);

  return res.json({
    code: 200,
    data: {
      out_trade_no: order.out_trade_no,
      status:       order.status,       // "PENDING" | "SUCCESS" | "FAILED"
      amount:       order.amount,
    },
  });
});

// GET /health
app.get("/health", (req, res) => {
  res.json({
    status:              "ok",
    server:              "miniapp-backend",
    time:                new Date().toISOString(),
    appsecret_set:       APPSECRET !== "YOUR_APPSECRET_FROM_TCSAS_CONSOLE",
    merchant_key_set:    !!MERCHANT_PRIVATE_KEY,
    users_in_memory:     Object.keys(users).length,
    orders_in_memory:    Object.keys(orders).length,
  });
});

const PORT = process.env.MINIAPP_PORT || 3000;
app.listen(PORT, () => {
  console.log(`\n✅ MiniApp Backend (Payment) running on http://localhost:${PORT}`);
  console.log(`   APPSECRET set:       ${APPSECRET !== "YOUR_APPSECRET_FROM_TCSAS_CONSOLE" ? "YES ✅" : "NO ❌"}`);
  console.log(`   MERCHANT_PRIVATE_KEY: ${MERCHANT_PRIVATE_KEY ? "YES ✅" : "NO ❌ (using mock paySign)"}`);
  console.log(`   MINIAPP_BACKEND_URL: ${MINIAPP_BACKEND_URL}`);
  console.log(`\n   Endpoints:`);
  console.log(`   POST /getUserInfo        — login`);
  console.log(`   POST /payOrderV3         — create order + get payment params`);
  console.log(`   POST /notify_payBack     — SAS delivery notification (ACK)`);
  console.log(`   POST /queryPayResult     — mini program polling`);
  console.log(`   GET  /health             — health check`);
});
