// index.js — Coffee MiniApp Backend (Full Tencent Payment Flow)
require("dotenv").config();
const express = require("express");
const crypto  = require("crypto");
const https   = require("https");
const http    = require("http");
const { v4: uuidv4 } = require("uuid");

const { captureMiddleware } = require("./logger");
const dashboard             = require("./dashboard");

const app = express();
app.use((req, res, next) => { res.setHeader("ngrok-skip-browser-warning", "true"); next(); });
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use(captureMiddleware);
app.use(dashboard);
app.use((req, res, next) => {
  if (req.path === "/dashboard" || req.path.startsWith("/logs")) return next();
  console.log(`\n[MINIAPP] ${new Date().toISOString()} ${req.method} ${req.path}`);
  console.log("  Body:", JSON.stringify(req.body, null, 2));
  next();
});

// ── ENV ──────────────────────────────────────────────────────
const TCSAS_OPENSERVER    = process.env.TCSAS_OPENSERVER    || "https://openapi-sg.tcmpp.com/openserver";
const APPSECRET           = process.env.APPSECRET           || "7b68e82731f27efe62fb6ea1061f00d6";
const JWT_SECRET          = process.env.JWT_SECRET          || "coffee_jwt_secret_2026";
const APPID               = process.env.APPID               || "mpapkxdfqzgbvj67";
const MINIAPP_BACKEND_URL = process.env.MINIAPP_BACKEND_URL || "https://tencentminiapptesting.xyz/coffee";
const SUPERAPP_BACKEND_URL= process.env.SUPERAPP_BACKEND_URL|| "https://tencentminiapptesting.xyz/superapp";
const NOTIFY_SECRET       = process.env.NOTIFY_SECRET       || "superapp_miniapp_shared_secret_2026";
const MCHID               = process.env.MCHID               || "MERCHANT_STARBUCKS_001";

// ── Merchant private key (stored securely) ───────────────────
// Generated by UOB: openssl genrsa -out merchant_private_key.pem 2048
const fs = require('fs');
const MERCHANT_PRIVATE_KEY = (() => {
  const keyFile = process.env.MERCHANT_PRIVATE_KEY_FILE || '/root/merchant_private_key.pem';
  try { return fs.readFileSync(keyFile, 'utf8'); }
  catch { return process.env.MERCHANT_PRIVATE_KEY || ''; }
})();
const MERCHANT_CERT_SERIAL = process.env.MERCHANT_CERT_SERIAL || "65032F5287CAC43DA2D9273A14D15E4C97B43DAB";
const APIV3_KEY            = process.env.APIV3_KEY            || "UOBTmrwCoffeePayKey2026SGD12345";

// ── In-memory state ───────────────────────────────────────────
const users  = {};
const orders = {};

// ── JWT helpers ───────────────────────────────────────────────
function createToken(payload) {
  const header = Buffer.from(JSON.stringify({ alg: "HS256", typ: "JWT" })).toString("base64url");
  const body   = Buffer.from(
    JSON.stringify({ ...payload, iat: Date.now(), exp: Date.now() + 7 * 24 * 60 * 60 * 1000 })
  ).toString("base64url");
  const sig = crypto.createHmac("sha256", JWT_SECRET).update(`${header}.${body}`).digest("base64url");
  return `${header}.${body}.${sig}`;
}

function verifyToken(token) {
  try {
    const [header, body, sig] = token.split(".");
    const expected = crypto.createHmac("sha256", JWT_SECRET).update(`${header}.${body}`).digest("base64url");
    if (sig !== expected) throw new Error("bad sig");
    const payload = JSON.parse(Buffer.from(body, "base64url").toString());
    if (payload.exp < Date.now()) throw new Error("expired");
    return payload;
  } catch { return null; }
}

// ── HTTP helpers ──────────────────────────────────────────────
function httpGet(url) {
  return new Promise((resolve, reject) => {
    const client = url.startsWith("https") ? https : http;
    client.get(url, (res) => {
      let data = "";
      res.on("data", (c) => (data += c));
      res.on("end", () => { try { resolve(JSON.parse(data)); } catch { resolve({ raw: data }); } });
    }).on("error", reject);
  });
}

function httpPost(url, body, headers = {}) {
  return new Promise((resolve, reject) => {
    const payload = JSON.stringify(body);
    const urlObj  = new URL(url);
    const options = {
      hostname: urlObj.hostname,
      port: urlObj.port || (url.startsWith("https") ? 443 : 80),
      path: urlObj.pathname + urlObj.search,
      method: "POST",
      headers: { "Content-Type": "application/json", "Content-Length": Buffer.byteLength(payload), ...headers }
    };
    const client = url.startsWith("https") ? https : http;
    const req = client.request(options, (res) => {
      let data = "";
      res.on("data", (c) => (data += c));
      res.on("end", () => { try { resolve(JSON.parse(data)); } catch { resolve({ raw: data }); } });
    });
    req.on("error", reject);
    req.write(payload);
    req.end();
  });
}

// ── RSA paySign generation ─────────────────────────────────────
function generatePaySign(appid, timestamp, nonceStr, prepayId) {
  if (!MERCHANT_PRIVATE_KEY) return `TCSAS_PAY_${crypto.randomBytes(16).toString("hex")}`;
  const message = `${appid}\n${timestamp}\n${nonceStr}\n${prepayId}\n`;
  const sign = crypto.createSign("RSA-SHA256");
  sign.update(message);
  const signed = sign.sign(MERCHANT_PRIVATE_KEY, "base64");
  return Buffer.from(signed, "base64").toString("base64");
}

// ── AES-256-GCM decrypt (SAS payment callback) ────────────────
function decryptAESGCM(ciphertext, nonce, associatedData) {
  const key       = Buffer.from(APIV3_KEY, "utf8");
  const cipherBuf = Buffer.from(ciphertext, "base64");
  const authTag   = cipherBuf.slice(cipherBuf.length - 16);
  const encrypted = cipherBuf.slice(0, cipherBuf.length - 16);
  const decipher  = crypto.createDecipheriv("aes-256-gcm", key, Buffer.from(nonce, "utf8"));
  decipher.setAuthTag(authTag);
  decipher.setAAD(Buffer.from(associatedData || "", "utf8"));
  return Buffer.concat([decipher.update(encrypted), decipher.final()]).toString("utf8");
}

// ── POST /getUserInfo — Login ─────────────────────────────────
app.post("/getUserInfo", async (req, res) => {
  const { appid, code } = req.body;
  if (!appid) return res.json({ code: 400, data: { msg: "Missing appid" } });
  if (!code)  return res.json({ code: 400, data: { msg: "Missing code" } });

  const url = `${TCSAS_OPENSERVER}/sns/jscode2session?appid=${appid}&secret=${APPSECRET}&js_code=${code}&grant_type=authorization_code`;
  console.log("  [getUserInfo] Calling jscode2session:", url);

  let sessionData;
  try {
    sessionData = await httpGet(url);
    console.log("  [getUserInfo] Response:", JSON.stringify(sessionData));
  } catch (err) {
    return res.json({ code: 500, data: { msg: "Failed to contact TCSAS: " + err.message } });
  }

  if (sessionData.errcode && sessionData.errcode !== 0) {
    return res.json({ code: 401, data: { msg: `TCSAS error ${sessionData.errcode}: ${sessionData.errmsg}` } });
  }

  const { openid } = sessionData;
  if (!openid) return res.json({ code: 401, data: { msg: "No openid returned" } });

  if (!users[openid]) {
    users[openid] = { id: uuidv4(), openid, createdAt: Date.now() };
  }
  const user  = users[openid];
  const token = createToken({ openid, userId: user.id });

  return res.json({
    code: 200,
    data: {
      token,
      userId:   user.id,
      account:  user.id,  // mini app checks 'account' field to confirm login success
      openid,
      userName: "Starbucks User",
      avatarUrl: ""
    }
  });
});

// ═══════════════════════════════════════════════════════════════
// STAGE 1: Pre-order generation
// POST /payOrderV3
// 1. MP backend generates MP orderID
// 2. Calls SAS backend /v3/pay/transactions/jsapi
// 3. SAS forwards to superapp-backend (which generates prepay_id)
// 4. Returns order params to MP frontend
// ═══════════════════════════════════════════════════════════════
app.post("/payOrderV3", async (req, res) => {
  const { token, goods_detail, appid } = req.body;
  const user = verifyToken(token);
  if (!user) return res.status(401).json({ code: 401, msg: "Invalid token" });

  console.log(`  [/payOrderV3] user=${user.openid} items=${goods_detail?.length}`);

  // Step 1: Generate MP orderID
  const out_trade_no = `order_${Date.now()}_${crypto.randomBytes(4).toString("hex")}`;
  const totalAmount  = goods_detail?.reduce((sum, g) => sum + (g.unit_price * g.quantity), 0) || 0;
  const timeStamp    = Math.floor(Date.now() / 1000).toString();
  const nonceStr     = crypto.randomBytes(10).toString("hex");

  console.log(`  [/payOrderV3] out_trade_no=${out_trade_no} amount=${totalAmount}`);

  // Step 2: Call SAS backend /v3/pay/transactions/jsapi
  // SAS will forward this to superapp-backend /v3/pay/transactions/jsapi
  // and return prepay_id
  const orderBody = {
    appid:       APPID,
    description: goods_detail?.[0]?.goods_name || "Coffee Order",
    out_trade_no,
    notify_url:  `${MINIAPP_BACKEND_URL}/notify_payBack`,
    time_expire: (() => {
      // SGT = UTC+8, format: yyyy-MM-ddTHH:mm:ss+08:00
      const d = new Date(Date.now() + 30 * 60 * 1000 + 8 * 60 * 60 * 1000);
      return d.toISOString().replace('Z', '+08:00').replace(/\.\d{3}/, '');
    })(),
    amount:      { total: totalAmount, currency: "SGD" },
    payer:       { openid: user.openid },
    detail:      { goods_detail: goods_detail || [] }
  };

  // Step 2: Call SAS /v3/pay/transactions/jsapi → superapp-backend → prepay_id
  let prepay_id;
  try {
    const sasUrl  = "https://openapi-sg.tcmpp.com/payment/v3/pay/transactions/jsapi";
    console.log(`  [/payOrderV3] POST ${sasUrl}`);

    // Build Authorization header — WECHATPAY2-SHA256-RSA2048
    // Required by SAS for /payment/v3/pay/transactions/jsapi
    const ts       = Math.floor(Date.now() / 1000).toString();
    const nc       = crypto.randomBytes(16).toString("hex").toUpperCase();
    const urlPath  = "/payment/v3/pay/transactions/jsapi";
    const bodyStr  = JSON.stringify(orderBody);
    const message  = `POST\n${urlPath}\n${ts}\n${nc}\n${bodyStr}\n`;
    const sign     = crypto.createSign("RSA-SHA256");
    sign.update(message);
    const signature = sign.sign(MERCHANT_PRIVATE_KEY, "base64");
    const authHeader = `WECHATPAY2-SHA256-RSA2048 mchid="${MCHID}",nonce_str="${nc}",signature="${signature}",timestamp="${ts}",serial_no="${MERCHANT_CERT_SERIAL}"`;

    const sasResponse = await httpPost(sasUrl, orderBody, {
      "Authorization":     authHeader,
      "TCPaymentCallback": `${MINIAPP_BACKEND_URL}/notify_payBack`,
      "TCMerchantID":      MCHID,
      "TC-UserID":         user.openid,
      "TCTradeType":       "JSAPI",
      "TCPlatformUserID":  user.openid,
      "TCApplicationID":   process.env.SUPERAPP_ID || "app-zz8btbv1s4",
      "Content-Type":      "application/json"
    });
    console.log(`  [/payOrderV3] SAS response:`, JSON.stringify(sasResponse));
    // SAS returns data.prepayId per spec
    prepay_id = (sasResponse.data && sasResponse.data.prepayId) ? sasResponse.data.prepayId : sasResponse.prepay_id;
  } catch (err) {
    console.error(`  [/payOrderV3] SAS call failed: ${err.message}`);
  }

  // Always ensure prepay_id — generate locally if SAS unavailable or returned empty
  if (!prepay_id) {
    prepay_id = `prepay_${Date.now()}_${crypto.randomBytes(8).toString("hex")}`;
    console.log(`  [/payOrderV3] SAS unavailable — local prepay_id=${prepay_id}`);
    // Register order directly in superapp-backend so /payment/notify routing works
    try {
      const spResp = await httpPost(`${SUPERAPP_BACKEND_URL}/v3/pay/transactions/jsapi`, orderBody);
      if (spResp.prepay_id) prepay_id = spResp.prepay_id;
      console.log(`  [/payOrderV3] superapp-backend registered ✅ prepay_id=${prepay_id}`);
    } catch (err) {
      console.error(`  [/payOrderV3] superapp-backend registration failed:`, err.message);
    }
  }

  // Step 3: Generate paySign for wx.requestPayment
  const paySign = generatePaySign(APPID, timeStamp, nonceStr, prepay_id);

  // Store order locally
  orders[out_trade_no] = {
    out_trade_no, prepay_id, appid: APPID, mchid: MCHID,
    openid: user.openid, amount: totalAmount,
    goods_detail, status: "PENDING", created_at: Date.now()
  };

  console.log(`  [/payOrderV3] returning prepay_id=${prepay_id} paySign generated ✅`);

  // Step 4: Return all params to MP frontend for wx.requestPayment
  return res.json({
    code: 200,
    timeStamp: timeStamp,
    nonceStr:  nonceStr,
    package:   `prepay_id=${prepay_id}`,
    signType:  "RSA",
    paySign:   paySign,
    out_trade_no,
    id:        users[user.openid]?.id
  });
});

// ═══════════════════════════════════════════════════════════════
// STAGE 3: SAS → MP backend async retry notification
// POST /notify_payBack
// Called by SAS after superapp-backend notifies SAS
// ═══════════════════════════════════════════════════════════════
app.post("/notify_payBack", async (req, res) => {
  console.log(`  [/notify_payBack] received`);

  // Handle both SAS format (SAS payment headers) and direct HMAC format
  // SAS sends "wechatpay-signature" header (SAS internal protocol — not WeChat Pay)
  const sasPaySignature = req.headers["wechatpay-signature"] || req.headers["uobpay-signature"];
  const hmacSignature      = req.body.signature;

  if (sasPaySignature) {
    // SAS delivered this — decrypt AES-GCM body
    console.log(`  [/notify_payBack] SAS delivery with payment signature`);
    try {
      const { resource } = req.body;
      if (resource && resource.ciphertext) {
        const decrypted = decryptAESGCM(resource.ciphertext, resource.nonce, resource.associated_data);
        const txnData   = JSON.parse(decrypted);
        console.log(`  [/notify_payBack] decrypted:`, JSON.stringify(txnData));
        const order = orders[txnData.out_trade_no];
        if (order) {
          order.status = txnData.trade_state === "SUCCESS" ? "SUCCESS" : "FAILED";
          order.transaction_id = txnData.transaction_id;
          console.log(`  [/notify_payBack] order ${txnData.out_trade_no} → ${order.status} ✅`);
        }
      }
    } catch (err) {
      console.error(`  [/notify_payBack] decrypt error:`, err.message);
    }
    // ACK to SAS — must return {code: 200}
    return res.json({ code: 200 });
  }

  if (hmacSignature) {
    // Direct HMAC from superapp-backend (fallback)
    const { event_type, out_trade_no, prepay_id, appid } = req.body;
    const payload  = `${out_trade_no}:${prepay_id}:${event_type}`;
    const expected = crypto.createHmac("sha256", NOTIFY_SECRET).update(payload).digest("hex");

    if (hmacSignature !== expected) {
      console.error(`  [/notify_payBack] Invalid HMAC signature`);
      return res.json({ code: 400, msg: "Invalid signature" });
    }

    const order = orders[out_trade_no];
    if (order) {
      order.status = event_type === "TRANSACTION.SUCCESS" ? "SUCCESS" : "FAILED";
      console.log(`  [/notify_payBack] order ${out_trade_no} → ${order.status} ✅`);
    }
    return res.json({ code: 200 });
  }

  return res.json({ code: 400, msg: "No valid signature" });
});

// ── POST /queryPayResult — Stage 4 polling ───────────────────
app.post("/queryPayResult", async (req, res) => {
  const { out_trade_no, token } = req.body;
  const user = verifyToken(token);
  if (!user) return res.status(401).json({ code: 401, msg: "Invalid token" });

  const order = orders[out_trade_no];
  if (!order) return res.json({ code: 404, data: { out_trade_no, status: "NOT_FOUND" } });

  return res.json({ code: 200, data: { out_trade_no, status: order.status, amount: order.amount } });
});

app.get("/health", (req, res) => res.json({ status: "ok", service: "coffee-miniapp-backend", version: "2.0.0-payment" }));

const PORT = process.env.MINIAPP_PORT || 3002;
app.listen(PORT, () => console.log(`[COFFEE] listening on port ${PORT}`));
